spring.application.name=user-service
server.port=8081

# Hibernate settings for SQLite

# The path to your database file (it will be created if it doesn't exist)
spring.datasource.url=jdbc:sqlite:mydb.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite doesn't use a username/password, but Spring needs these defined
spring.datasource.username=sa
spring.datasource.password=sa
# Hibernate Dialect for SQLite (Required for JPA/Hibernate 6+)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
jwt.secret=mysupersecretkeymysupersecretkey1234567890abcdeffedcba0987654321
jwt.expiration=3600000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.lease-renewal-interval-in-seconds=30


