spring.application.name=product-service

# The path to your database file (it will be created if it doesn't exist)
spring.datasource.url=jdbc:sqlite:productdb.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
jwt.secret=mysupersecretkeymysupersecretkey1234567890abcdeffedcba0987654321
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

