spring.application.name=ProjRAGAI
server.port=8084
# RabbitMQ Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Gemini Config
langchain4j.google-ai-gemini.chat-model.api-key=AIzaSyCeojygsYZQzvLmxYvdAsyNsLXTR6DvRV4
langchain4j.google-ai-gemini.chat-model.model-name=gemini-flash-latest
#langchain4j.google-ai-gemini.chat-model.api-version=v1beta